name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create new file
      run: |
        DATE=$(date +'%Y-%m-%d')
        echo "Automated commit on $DATE" > daily-commit-$DATE.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated commit on ${{ env.DATE }}"
        file_pattern: 'daily-commit-*.txt'
